/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proccessdaemon_aven_com_proccessdaemon_Watcher */

#ifndef _Included_proccessdaemon_aven_com_proccessdaemon_Watcher
#define _Included_proccessdaemon_aven_com_proccessdaemon_Watcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     proccessdaemon_aven_com_proccessdaemon_Watcher
 * Method:    createWatcher
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_proccessdaemon_aven_com_proccessdaemon_Watcher_createWatcher
  (JNIEnv *, jobject, jstring);

/*
 * Class:     proccessdaemon_aven_com_proccessdaemon_Watcher
 * Method:    connectToMonitor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_proccessdaemon_aven_com_proccessdaemon_Watcher_connectToMonitor
  (JNIEnv *, jobject);

/*
 * Class:     proccessdaemon_aven_com_proccessdaemon_Watcher
 * Method:    sendMsgToMonitor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_proccessdaemon_aven_com_proccessdaemon_Watcher_sendMsgToMonitor
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL JNI_OnLoad( JavaVM* , void* );

#ifdef __cplusplus
}
#endif
#endif
